docs/source/introduction.rst

Use rst syntax for link in install instructions

---

fs/compress.py
fs/opener.py
fs/tarfs.py
fs/test.py
fs/zipfs.py
tests/test_archives.py
tests/test_opener.py
tests/test_tarfs.py

This PR contains edits to support Tar archives (through python **tarfile** module).
I tried to be consistent with the ZipFS implementation, although since tar archives are much more Linux-friendly, there was no need for the mirrored MemoryFS for ReadTarFS.
For the tar formats, supported compressions are 'gz', 'bz2', and 'xz' for Python3 only. When a TarFS is created, the compression is guessed from the file extension, but if needed it can be given with the `compression` argument as well.
I also added tests, based on the zipfs tests, and tried to stay as clear as possible. Tell me if you have any questions.

Add support for tar (TarFS) and tests

---

fs/osfs.py
tests/test_osfs.py

It seems that os.pathconf has issues with unicode paths in Python 2 as it tries to decode to ascii despite locale settings. It string is encoded to bytes first, then everything works fine.
Tested on linux-3.13.0-110-generic/Python 2.7.6.

Fixed UnicodeEncodeError when creating OSFS from non-ascii path

---

requirements.txt
setup.py

I just made the `enum32` a conditional requirement depending on the python version ;  this should be enough to fix #41.

Use PEP-496 syntax to resolve #41

---

docs/source/guide.rst

In ab15ba72d885cf8b02ed14009d551a9a9aa61957 the code for Walker() was [changed](https://github.com/PyFilesystem/pyfilesystem2/commit/ab15ba72d885cf8b02ed14009d551a9a9aa61957#diff-edbf11fed744b9aee494554ab2d36c74L119) to accept "filter" instead of "wildcards". The documentation was also [changed](https://github.com/PyFilesystem/pyfilesystem2/commit/ab15ba72d885cf8b02ed14009d551a9a9aa61957#diff-edd835f0f9f7dac8265dec2cc5776a67L131) but from "wildcards" to "files" which is wrong, obviously.

Fix documentation for "Moving and Copying"

---

fs/osfs.py
requirements.txt
setup.py
tests/test_osfs.py
tox.ini

Hi,
I just noticed while trying to install `fs` on the `alpine-python` Docker image that it had `scandir` as a hard requirement. Since `scandir` is a C extension, this meant that **1.** implementations other than CPython couldn't use *Pyfilesystem2*, and that **2.** it required C compilation, so minimal builds needed to have both a C compiler and Python headers installed, both of which can weigh a lot. 
With the edits in that PR, the `scandir` module will be used if it can be found (either `scandir` is installed or the version is superior to **3.5**). In other cases, plain `os.listdir` module will be used.

Make scandir an optional dependency

---

fs/ftpfs.py
fs/iotools.py
fs/memoryfs.py
fs/test.py

* made `FTPFile`, `_MemoryFile` and `RawWrapper` derive from `io.IOBase`
* removed `__enter__`, `_del__` and `__exit__` implementation as the base `io.IOBase` implementation returns `self` in `__enter__` and closes `self` in `__exit__` and `__del__` already.
* removed `RawWrapper` `next` and `__next__` as they only copied the base `io.IOBase` implementation
* implemented `writable` and `readable` depending on the mode of `FS.open` for `FTPFile` and `_MemoryFile`
* implemented `seekable` (always returning `True`) for all three classes
* Check file objects returned by `FS.open` and `FS.openbin` are instances of `io.IOBase`
* Check that `readable` and `writable` return the right value depending on the opening mode
* Check that file objects are not closed within a context block, then closed …

Feat iobase (PR for #50)

---

fs/base.py
fs/opener/ftpfs.py
fs/subfs.py
fs/test.py
fs/wrapfs.py

Implements `ClosingSubFS` which is identical to `SubFS` but will close its parent automatically.
This was a work-around to https://github.com/PyFilesystem/pyfilesystem2/issues/51

ClosingSubFS

---

fs/base.py
fs/ftpfs.py
fs/memoryfs.py
fs/test.py
testrequirements.txt
tests/test_ftpfs.py

Hi Will, I updated the tests in `fs.test` with some missing checks, and discovered some new bugs I will fix gradually in this PR.
1. `FS.copy`, `FS.move`, `FS.copydir` and `FS.movedir` should raise `ResourceNotFound` when the source is nowhere to be found
2. `FS.copy` and `FS.move` should probably raise `FileExpected` when the source is a directory (not listed in the documentation, but makes sense I guess ?...)
3. `FS.movedir` and `FS.copydir` should raise `DirectoryExpected` when the source is a file
4. If a filesystem is advertising itself as *case insensitive*, check that's true
5. If a filesystem is advertising itself as supporting *unicode paths*, check that's true
6. Check that *file-like* objects returned by `FS.openbin`:
* have a `seek` method that returns the new absolute …

Update tests, and fix discovered bugs

---

fs/errors.py

`ResourceReadOnly` was missing from `fs.errors.__all__`, hence not documented by automodule.

Add `ResourceReadOnly` to `__all__` in `fs.errors`

---

fs/filesize.py
tests/test_filesize.py

According to [Wikipedia](https://en.wikipedia.org/wiki/Byte), the binary filesize units should be `KiB`, `MiB`, ..., and the decimal units should be `kB`, `MB`, ...
Previously, `traditional` would use the SI prefixes, and `decimal` would display bits instead of bytes.
Also, I'm not sure about this, but once again functions should probably be raising `TypeError` when given an argument that cannot be coerced to a numerical value.

Fix units in `fs.filesize`

---

CHANGELOG.md
fs/ftpfs.py
tests/test_ftpfs.py

Work in Progress
Handle utf8 encoding for ftp servers without opening another connection.
Also ensures that features are requested after login.

better handling of ftp features

---

fs/compress.py
fs/tarfs.py
fs/zipfs.py
tests/test_archives.py
tests/test_tarfs.py
tests/test_zipfs.py

The objects returned by `ZipFile.open` do not support seeking, but since they use an internal buffer we can use that buffer to our advantage. So here's what I did:
* `_ZipExtFile.seek` will try to use the internal zip buffer as much as possible, by manually changing the position of the internal file object in the buffer. If it's not possible, then: 
- if we're seeking backward, we will have to open the file one more time (like `FTPFile` does)
- if we're seeking forward, we read and discard until we reach the desired position
* `_ZipExtFile.read` and `_ZipExtFile.read1` were patched to prevent the internal file object from discarding the read buffer on EOF. Without this fudge, we would have to reopen the file each time the EOF is reached, even for a `_ZipExtFile.seek(-1, Seek.end)`.
* …

Seek files and extract permissions from `ZipFS`

---

CHANGELOG.md
fs/_version.py
fs/path.py
fs/walk.py
fs/zipfs.py
tests/test_path.py
tests/test_walk.py

**Work in progress.**
Adds a max_depth parameter to fs.walk.

added max_depth

---

fs/zipfs.py
tests/test_zipfs.py

Using the lower level interface is:
* highly implementation-specific
* harder to understand
* generating bugs
This PR reverts back to a purely emulated seeking feature, i.e. *seeking forward by reading*.

Revert back to emulate `ZipExtFile.seek`

---

tests/test_ftp_parse.py

the embedded UNIX epoch values assumed that tm_year is 2017

Fix test_ftp_parse to pass in 2018

---

fs/path.py
tests/test_path.py

Child and parent pathes were swapped by mistake. Documentation example for isbase didn't work because of that

Fixed isbase method

---

fs/base.py
fs/wrapfs.py
tests/test_walk.py

I needed to write custom walker for my custom fs. It was done via override of 'walk' property. Everything was fine until I opened subdir. It turned out that WrapFS inherits 'walk' property from base FS, which always uses default Walker class. 
I propose introduction of 'walker_class' fs class-level attribute which is used in 'walk' propery instead of hard-coded Walker class. With this, custom fs will only need to redefine it to use another walker.

walker_class attribute for filesystem

---

CHANGELOG.md
docs/source/implementers.rst
fs/_version.py
fs/base.py
fs/copy.py
fs/test.py
tests/test_ftpfs.py

Adds an `extract` method to base, to help with https://github.com/PyFilesystem/s3fs/issues/18
It should allow 'downloading' of files without the need for a temp file. The default is a simple file copy loop.
Open to suggestions re naming. Is `extract` appropriate?
@althonos

added extract method

---

.travis.yml
CHANGELOG.md
fs/compress.py
fs/copy.py
fs/mirror.py
fs/mountfs.py
fs/multifs.py
fs/test.py
fs/walk.py
tests/test_walk.py

This modifies the walk code to use iterators over lists where possible.
This is so that the `info`, `files` and `dirs` methods don't need to load an entire directory worth before they start yielding results--which should also be more memory efficient.
See https://github.com/PyFilesystem/pyfilesystem2/issues/112
Also includes some optimisations for file copying which will benefit S3FS and potentially other network filesystems that implement `getfile`.

Walk iterators

---

fs/errors.py
fs/osfs.py
fs/tarfs.py
fs/zipfs.py
tests/test_errors.py

Hi Will,
I made it so `CreateFailed` accepts an additional `exc` argument, as discussed in #144.
I also added a decorator classmethod to `CreateFailed`, so that it is easier to wrap any errors occuring in a filesystem `__init__` method into a `CreateFailed` exception.

Allow wrapping exceptions in `CreateFailed`

---

fs/tarfs.py
tests/test_tarfs.py

Hi Will, 
just a quick PR to fix #160, with regression tests. Is there any `unique` iterator filter in the `fs` codebase ? It could avoid using a set just to filter out duplicates in the `listdir` patch.

Fix issue #160 (TarFS implicit directory bug)

---

fs/test.py

Hi Will,
this small(est) PR intends to fix a possible bug with the test case, where `f.write('no')` could possibly fail with a `TypeError` (since `f` is open in binary mode) before raising the expected `IOError`.

Fix wrong type in `test_open_files`

---

testrequirements.txt

Enforce `PyYAML < 4` when testing against Python3.3

---

.travis.yml
tests/test_opener.py

Proposed fix for #185 :
Instead of monkey patching `issubclass` for it to accept `MagicMock` as an `Opener` subclass, I create a mock opener that raises a `ValueError` on instantiation. Less dirty, and works on Python 3.7.

Fix `test_entry_point_create_error` (fix #185)

---

fs/base.py

Match with the docs for `FS.setbytes` because they're different versions
of essentially the same thing: setX to a file, so `path` is exactly the same
and `contents` is adapted for this function.

Fix parameter docs for `FS.settext`

---

fs/osfs.py

`io.open()` takes a file descriptor, `os.open()` returns one and lets you pass O_EXCL to open the file.

Use `os.open()` in osfs in exclusive mode (#182)

---

fs/errors.py
tests/test_errors.py

This is a fix for the problem of subclasses of FSError/Exception causing multiprocessing to hang ( issue #183 ) if they change the arguments to `__init__`.  I went with @willmcgugan 's suggestion to implement `__reduce__` in each subclass wherever it was required.

Fix multiprocessing hang on FSErrors

---

tests/test_opener.py

This time I tested using the Docker `python:3.7-alpine` image, so hopefully this should be fine.
```shell
Ran 1513 tests in 42.330s
OK (passes=1488, skips=25)
```

Fix tests against Python 3.7

---

CHANGELOG.md
docs/source/conf.py
docs/source/globbing.rst
docs/source/guide.rst
docs/source/index.rst
docs/source/reference.rst
docs/source/reference/glob.rst
fs/_bulk.py
fs/_version.py
fs/base.py
fs/copy.py
fs/glob.py
fs/test.py
fs/wildcard.py
requirements.txt
tests/test_copy.py
tests/test_errors.py
tests/test_glob.py

An implementation of 'glob' for Pyfilesystem.
This finds all Python files in the root directory:
```python
for path, info my_fs.glob("*.py"):
print(path)
```
This finds all Python files in sub directories:
```python
for path, info my_fs.glob("*/*.py"):
print(path)
```
This finds all Python files recursively:
```python
for path, info my_fs.glob("**/*.py"):
print(path)
```
This finds all the .git directories:
```python
for path, info in my_fs.glob("**/.git/"):
print(path)
```
Similar to `walk`, `glob` is a callable object, which you can either iterate over or call its methods.
This counts the number of bytes in Python files recursively:
```python
print(my_fs.glob("**/*.py").count())
```
This removes all `pyc` file recursively:
```python
my_fs.glob("**/*.pyc").remove()
```
Many other …

implementation of glob

---

fs/test.py

Few minor improvement of `fs.test.test_listdir`:
1. Listing over files _and_ a directory. This would have caught a bug I int in my GCSFS implementation: A `fs.listdir`on the new example would have resulted in `["foo", "bar", "baz/"]` which is incorrect.
2. Added a file in a subdirectory which should not be listed (easy mistake when trying to implement an object store where every "list" is actually a "walk"). This was caught by other unit tests but I think the check makes sense here.
3. The unicode check was duplicated, the same check is done a few lines further down

minor improvements and cleanup at fs.test.test_listdir

---

fs/ftpfs.py
fs/osfs.py
fs/test.py

Also doing the exclusive thing properly in openbin.
(#182)
I think the OS_RDWR behaviour is correct since if you specify `x` mode, you can't specify `r` or `w`. So it implies both. I'm pretty sure this is what Python 3 does so the `fs` package API should be consistent in both versions of Python here.

Use os.O_RDWR for exclusive mode in Python 2.7

---

fs/osfs.py
setup.py
tests/test_osfs.py

Hi Will,
while toying with the `sendfile` syscall I noticed that it could also be used to copy files on the OS filesystem quicker than with a chunk copy, and of course people already patched the `shutil` module to use it (see [python#33671](https://bugs.python.org/issue33671)). 
I backported the patch of [`pyfastcopy`](https://pypi.org/project/pyfastcopy/) so that `OSFS.copy` will use `sendfile` if it is available (as either `os.sendfile` or `sendfile.sendfile` from [`pysendfile`](https://pypi.org/project/pysendfile)) and falling back to `shutil.copyfile` if it is not supported on the local platform.
It may also be a good idea to use `sendfile` and `shutil.copy` in `fs.copy.copy_file` and `fs.copy.copy_file_internal` if both source and destination files have a syspath. Tell me what you …

Implement OSFS.copy using sendfile or shutil.copy

---

fs/_ftp_parse.py
tests/test_ftp_parse.py

We had some problems trying to connect to a Windows NT FTP server. FTP LIST lines look totally different from the linux ones, therefore we needed another regex parser and decoder in the `_ftp_parse.py` file. I tested it against this server and our requirements (list directories, create directories, create files) work fine. But let me know if this PR doesn't match your style or if I have to do something else/different. Best regards!
Support for Windows NT lines `ftpfs.py:_read_dir()`:
```python
[
'11-02-18  02:00PM       <DIR>          asdf',
'11-02-18  01:50PM       <DIR>          data',
'11-01-18  01:41PM       <DIR>          doc',
'11-02-18  02:12PM       <DIR>          images',
'11-02-18  03:33PM                 9276 logo.gif'
]
```

Support for Windows NT FTP servers

---

fs/opener/__init__.py
fs/opener/appfs.py
fs/opener/ftpfs.py
fs/opener/memoryfs.py
fs/opener/osfs.py
fs/opener/registry.py
fs/opener/tarfs.py
fs/opener/tempfs.py
fs/opener/zipfs.py
setup.py
tests/test_opener.py

Hi @willmcgugan, hi @justvanrossum,
this PR reverts back to the original Pyfilesystem2 opener behaviour, and manually installs openers from the `fs.opener` module. Additional extensions are loaded, and take priority over builtin filesystems (i.e. if an extension defines `tar` then it is used instead of the `fs.opener.tarfs.TarOpener`).
I added an optional kwarg to `Registry`, so that a `Registry` can disable loading external filesystems.  But because of variable shadowing, no `Registry` instance can be created outside of the `fs.opener.registry` module anyway (well, it's still possible through `sys.modules`).
Tests still passed on my machine with `fs.sshfs` installed.

Revert back to manual registry installation (fix #228)

---

fs/opener/appfs.py

Currently, `AppFS` won't create a new subdirectory even if `create` is set to `True`. Minimal failing example:
```python
import fs
fs.open_fs("userdata://fs:willmcgugan/test", create=True)
```
As a side note: maybe the `fs.base.FS.makedir` and `fs.base.FS.makedirs` could also take a `factory` argument like `fs.base.FS.opendir` does !

Fix `AppFS` failing to create missing dirs even on `create=True`

---

fs/opener/registry.py

Just noticed this as my `mypy` was complaining in another project because I passed an `FS` instance to `fs.open_fs`.

Fix type annotation of `fs.open_fs`

---

CHANGELOG.md
README.md
fs/ftpfs.py

Calling `self.ftp.voidresp()` before closing the FTPFile `write_conn` ensures that the last `write` operation completes before the connection is closed.
Solves #240

Call `self.ftp.voidresp()` before closing `write_conn`

---

CHANGELOG.md
fs/_version.py
fs/opener/registry.py
fs/osfs.py
tests/test_opener.py

A little polish for openers /  typing. Version bump.

Opener refinements

---

CHANGELOG.md
fs/opener/registry.py

Thank you for your pull request!
I made sure `Registry.install` returns its argument, otherwise it would not be possible to use it as a decorator as demonstrated in the docstring.

Fix `registry.install` not returning decorated class

---

CHANGELOG.md
fs/_version.py
fs/path.py

The `IllegalBackReference` exception has the following mangled error message:
```
fs.errors.IllegalBackReference: path 'Too many backrefs in '../foo'' contains back-references outside of filesystem
```
This was because `normpath` was passing in its own error rather than the path.
Fixed message is clearer:
```
fs.errors.IllegalBackReference: path '../foo' contains back-references outside of filesystem
```

fix for backref error

---

CHANGELOG.md
docs/source/implementers.rst
docs/source/interface.rst
fs/_version.py
fs/base.py
fs/errors.py
fs/info.py
fs/test.py
tests/test_new_name.py

Added FS.hash, a utility method to calculate the hash of a file, since its a fairly common requirement.
Wasn't certain if this belonged in the 'helper' methods or 'optional' methods. Settled on 'helper' because if a filesystem did expose a hash somehow, it could be exposed via FS.getinfo.

added hash method

---

CHANGELOG.md
fs/_version.py
fs/osfs.py
tests/test_osfs.py

When there are encoding issues in OSFS, a unicode decode error is raised. This can often be cryptic and breaks the promise that FS objects raise FS errors.
I've customized `OSFS.validatepath` to attempt a `fsencode` and raise a `InvalidCharsInPath` error when encoding fails. The error message also suggest to look at the env var LANG, which is a likely cause of encoding fails.

check invalid encoding in OSFS

---

CHANGELOG.md
fs/_version.py
fs/copy.py
fs/walk.py
tests/test_walk.py

Added an `exclude` argument to the walker, which excludes files matching any of the given patterns. This can be useful to ignore temporary or hidden files.
Also added `filter_dirs` argument to the walker, which will only recurse those directories which match any of the given filters. This one was mainly added for parity with other filter / exclude arguments. I can't actually think of a use case for this functionality!

Walk filter

---

CHANGELOG.md
fs/_version.py
fs/test.py
fs/wrapfs.py

WrapFS didn't contain the new 'hash' method. I think the only consequence of this would have been potentially incorrect error messages in exceptions.

Added hash method to wrapfs

---

CHANGELOG.md
fs/_version.py
fs/osfs.py
fs/tarfs.py
tests/test_tarfs.py

Fix exception when opening tar files (https://github.com/PyFilesystem/pyfilesystem2/issues/275)

fix for tarfs '.' exception

---

CHANGELOG.md
fs/osfs.py

The check for case insensitivity using `normcase` was unreliable, and failed on OSX. Found a "fix" here https://stackoverflow.com/questions/7870041/check-if-file-system-is-case-insensitive-in-python
I'm not too happy about this change as it requires writing to the filesystem to detect case insensitivity, which feels clumsy.

change case insensitivity test

---

docs/source/walking.rst
fs/base.py

I noticed a spelling error in the docs: "complement" was misspelled as "compliment".

Spelling: s/compliment/complement/

---

fs/ftpfs.py

A new method to get URL for FTP resource.
For example,
ftp://127.0.0.1/foo
ftp://127.0.0.1/foo/bar

Added geturl() method

---

CHANGELOG.md
fs/_version.py
fs/osfs.py
tests/test_osfs.py

Added an expand_vars flag to OSFS constructor to disable env var expansion.

add expand_vars flag

---

Makefile
docs/source/conf.py

Small Makefile tweaks, and fix the `ImportError: No module named 'fs'` error that `make docs` was giving me.

Add extra 'clean' rules to Makefile, and get 'make docs' working

---

CHANGELOG.md
CONTRIBUTORS.md
fs/ftpfs.py
tests/test_ftpfs.py

Now they should support user/passwd in URL.
Modified tests for ftp_url() and geturl() methods.

Added support for user/passwd in ftp_url().

---

CHANGELOG.md
CONTRIBUTORS.md
fs/memoryfs.py
tests/test_memoryfs.py

MemFS now immediately releases the memory used up by its files when `close()` is called, rather than when the file system gets garbage collected. Closes #308 .

[MemFS] Release memory when close() is called

---

.gitignore
fs/base.py
tests/test_subfs.py

Fixes #309. Allows filesystems to specify a custom type to replace the default SubFS, which is, by default, returned by opendir. Filesystem implementors should return their custom type from makedir(s), but existing filesystems will work unaltered.

Allow custom subfs

---

CHANGELOG.md
CONTRIBUTORS.md
fs/ftpfs.py
tests/test_ftpfs.py

Catch `EOFError` if thrown by an FTP operation and re-raise it as a `RemoteConnectionError`.
Closes #292.

[FTPFS] Handle EOFError

---

.travis.yml
CHANGELOG.md
fs/_fscompat.py
fs/_version.py
fs/glob.py
fs/memoryfs.py
fs/mode.py
fs/opener/registry.py
fs/osfs.py
testrequirements.txt

typing fixes

---

.travis.yml
CHANGELOG.md
appveyor.yml
docs/source/implementers.rst
fs/error_tools.py
fs/test.py
fs/walk.py
requirements.txt
setup.cfg
setup.py
testrequirements.txt
tests/conftest.py
tests/test_appfs.py
tests/test_base.py
tests/test_encoding.py
tests/test_ftp_parse.py
tests/test_ftpfs.py
tests/test_memoryfs.py
tests/test_opener.py
tests/test_osfs.py
tests/test_tarfs.py
tests/test_tempfs.py
tox.ini

Closes #327
* Migrate test suite from `nose` to `pytest`
* Randomized execution order of tests to expose interdependencies
* Overhauled Travis config to use tox environments instead of passing them in multiple places
* Fix a few `import mock` bugs that imported `mock` on Python 3 instead of the native module
* Remove unused imports in a few test files
* Remove `requirements.txt`, as it's out of date and no longer needed.
* Fixed abstract class imports from `collections` which will break on Python 3.8

Migrate tests to Pytest

---

.travis.yml
CHANGELOG.md
fs/ftpfs.py
fs/osfs.py
setup.py
tests/test_osfs.py

1. Only add `errno.ENOTSUP` to FTP failure codes if that's present.
2. Removed a few unused imports.
Closes #338

Fix missing ENOTSUP on PyPy

---

fs/test.py

Hi Will!
Just a quick bugfix since switching to `pytest` broke the CI of `fs.sshfs` and `fs.smbfs`, as I am not using `pytest` for these :smiley: 
Instead of using `pytest.skip`, raising `unittest.SkipTest` will be recognized in both `pytest` and non-`pytest` test harnesses, since `unittest` is pretty much the standard as it is part of the standard library.

Use `unittest.SkipTest` instead of `pytest.skip` in `fs.test`

---

.travis.yml
CHANGELOG.md

There's a problem with the SFTP server daemon in our tests that causes PyPy to fail on them (see #342). We can still test PyPy compatibility with other parts of the codebase without failing the build by using Travis' [`allow_failures`](https://docs.travis-ci.com/user/customizing-the-build/#rows-that-are-allowed-to-fail) directive. This will still run tests on PyPy, but won't fail the build if the PyPy builds don't pass. We can remove the `allow_failures` part once #342 is fixed.

Start testing PyPy

---

CHANGELOG.md
CONTRIBUTORS.md
fs/osfs.py
tests/test_osfs.py

This skips the copy tests when it hasn't been patched (i.e. Python 3.8+) while also reverting part of
6f89b81daab7b604a77eff232639b03b6fc55ab2 (do not patch copy for Python 3.8 whose `shutil.copy` implementation uses sendfile).

Do not test the patched copy implementation with Python 3.8+, fixes #421

---

fs/base.py

Adjust docstring to match function

---

CHANGELOG.md
CONTRIBUTORS.md
MANIFEST.in

Hi,
This will ensure the missing `conftest.py` file is included in source distributions (fixes #364), as well as the docs folder (useful for distros that build doc from the PyPI tarballs).

Include additional files in source distributions, fixes #364

---

CHANGELOG.md
CONTRIBUTORS.md
fs/_version.py
fs/base.py

Fixes an issue when docstrings are set to `None`. Issue #415.

None docstrings fix

---

CHANGELOG.md
CONTRIBUTORS.md
fs/_ftp_parse.py
tests/test_ftp_parse.py

By making this capture pattern non-greedy it will no longer
capture until the last AM or PM in a directory listing line.
Fixes #395 by using a non-greedy pattern for capturing the modified time from a NT directory listing (similar as is done for Linux)
Updated the WindowsNT test to catch a regression for this in the future.
```
coverage run -m pytest --cov-append .\tests\test_ftp_parse.py
=============================================================================== test session starts =============================================================================== 
platform win32 -- Python 3.7.2, pytest-4.6.5, py-1.8.1, pluggy-0.13.1
Using --randomly-seed=1589597818
rootdir: C:\dev\pyfilesystem2, inifile: setup.cfg
plugins: cov-2.7.1, randomly-3.0.0
collected 5 items …
```

Use a non-greedy pattern when capturing modified (#395)

---

CHANGELOG.md
docs/source/implementers.rst
fs/mode.py

- fixes #382 (Incorrect docstring of `Mode.to_platform_bin`)
- fixes #407 (Missing import in the testing example of the "Implementing Filesystems" section of the guide)

Documentation fixes for release v2.4.12

---

CHANGELOG.md
fs/ftpfs.py
fs/memoryfs.py
fs/test.py

- Bug fix
- Tests
- Add a test for `openbin` method in `FSTestCases` ensuring the returned object has a `mode` attribute containing the "b" flag.
- Fix `FTPFS.openbin` not implicitly converting mode to binary mode. Closes #406 .
- Add missing `mode` attribute to `_MemoryFile` objects created by `MemoryFS.openbin`.

Require `FS.openbin` to return a file-handle with in binary mode

---

CHANGELOG.md
CONTRIBUTORS.md
fs/ftpfs.py
fs/iotools.py
fs/memoryfs.py
fs/test.py

Added `readinto` method for `MemoryFS` file objects.  See #380 .

Add readinto method for MemoryFS and FTPFS file objects

---

CHANGELOG.md
CONTRIBUTORS.md
fs/_ftp_parse.py
tests/test_ftp_parse.py

Extended parsing compatibility of the FTP `LIST` command for Windows servers. Fixes #438 .
The parsing process now properly supports 24-hour time format, both with and without leading zeros. Unit tests were adapted accordingly.

Parsing compatibility of the FTP `LIST` command for Windows servers

---

.github/PULL_REQUEST_TEMPLATE.md
.travis.yml
CHANGELOG.md
CONTRIBUTORS.md
LICENSE
README.md
fs/_version.py
setup.cfg
setup.py

- Other
Here it is, release `v2.4.12`, a little more than one year after the previous one! The goal was to get some bug fixes before Python 2.7 reaches EOL.
About the project organisation:
- I moved `PULL_REQUEST_TEMPLATE.md` to `.github` and removed the check boxes from the categories, since GitHub would mistake them for a checklist.
- I added a copyright line about contributors in `LICENSE`.
- I replaced the `@willmcgugan` mention by `@Pyfilesystem/maintainers` in the pull request template.
- I added myself as a maintainer to the PyPI metadata 
- I moved all project metadata to `setup.cfg` instead of previously having half in `setup.py` and half in `setup.cfg`
Then we probably need to setup Travis-CI to deploy to PyPI, and we should be in the clear.
ping @PyFilesystem/maintainers

Prepare for release `v2.4.12`

---

fs/base.py
fs/test.py

A small docs improvement I came across while using the `fs.base.upload` method. It reflects the method throwing `ResourceNotFound` if the path you are uploading to does not exist.

Update base.fs.upload docs to reflect exceptions thrown

---

CHANGELOG.md
CONTRIBUTORS.md
fs/ftpfs.py
fs/opener/ftpfs.py
tests/test_ftpfs.py
tests/test_opener.py

- New feature
Added FTPS (FTP over TLS) support to FTPFS. Addresses #437.
* Try to import FTP_TLS from the standard library, but if it's not available just default to a plain FTP connection, and set the `tls` attribute to False
* Add a boolean `tls` argument to the constructor, and as an attribute
* Add details and examples to the class docstring
* Show the ftps:// scheme in the URL when TLS is enabled
* Enable TLS when the ftps:// scheme is used in open/open_fs
* Add basic test

FTPS support

---

CHANGELOG.md
fs/ftpfs.py
tests/test_ftpfs.py

- Other
(performance improvement)
Fixes #455
`_manage_ftp` opens a new FTP connection, which is not necessary in this case, as `self._lock` is obtained anyway.

In fs.ftpfs.FTPFS.upload, replaced `self._manage_ftp` by `self.ftp`.

---

CHANGELOG.md
fs/wrap.py
tests/test_wrap.py

- Bug fix
- Tests
This PR fixes the following issues:
- `fs.wrap.WrapReadOnly` did not wrap the `removetree` method, meaning a filesystem could still be wiped if this command was called. Closes #468 .
- `fs.wrap.WrapCachedDir` methods `isdir` and `isfile` would raise `ResourceNotFound` instead of returning `False` on non-existing paths. 
I also added more tests for these two classes, and in particular a test making sure `fs.copy`, `fs.move` and `fs.mirror` respect `WrapReadOnly` semantics; this is to avoid any new undetected removal that could occur if #429 or similar improvements are added which could use `os` functions to improve performance in various places when given filesystems with a syspath.

Fix miscellaneous bugs in `fs.wrap` 

---

CHANGELOG.md
fs/memoryfs.py
fs/test.py
tests/test_memoryfs.py

- New feature
This PR adds dedicated implementations for some `MemoryFS` methods that were still using the base `FS` code. This includes:
- `move` and `movedir`: the right directory entry is simply moved between folder, avoiding useless copy. Closes #452 .
- `removetree`: the entry is simply removed from its parents (in the case of `removetree("/")`, the entry is kept, but cleared)
- `scandir`: the entry being scanned is now kept in memory in a dedicated method (the base implementation uses `listdir` + `getinfo`, which caused `MemoryFS` to lookup for the parent folder over and over).

Add optimized implementations of several `MemoryFS` methods

---

CHANGELOG.md
fs/_ftp_parse.py
tests/test_ftp_parse.py

- Bug fix
The Linux regex in `fs._ftp_parse` was unable to recognize sticky/SUID/SGID bits in permissions. Closes #451, which was caused by a SGID bit. I also fixed the regex so that is can recognize more Unix file types, instead of just `-`, `l` or `d` as before.

Fix FTP not properly parsing lines with sticky/SUID/SGID permissions

---

CHANGELOG.md
fs/errors.py
tests/test_error_tools.py

- Bug fix
`fs.errors.PathError` was missing an `exc` argument, so it couldn't be used in `fs.error_tools.convert_os_errors`. This prevented the conversion of `OSError(errno.ENAMETOOLONG)` errors to `PathError`. Closes #453.

Add missing `exc` argument to `PathError`

---

CHANGELOG.md
fs/osfs.py
fs/test.py
tests/test_osfs.py

- Bug fix
Since Python 3.6, `os.scandir` returns an object that must be explicitly closed if the iteration stops before the iterator is exhausted. This PR does that, which should suppress `ResourceWarning` that were occasionally raised by an unclosed iterator in `OSFS.scandir`. I also changed the current `OSFS.scandir` code so that it only calls `stat` when necessary. Closes #311 .
I made it so `tests.test_osfs.TestOSFS` now treats warnings as errors, but it's still not 100% feasible to test this kind of warnings, because they are thrown on garbage collection, most of the time after our test case has finished running.

Fix minor issues in `OSFS.scandir`

---

CHANGELOG.md
fs/_ftp_parse.py
fs/_repr.py
fs/_url_tools.py
fs/base.py
fs/filesize.py
fs/ftpfs.py
fs/glob.py
fs/info.py
fs/opener/registry.py
fs/path.py
fs/permissions.py
fs/tarfs.py
fs/tempfs.py
fs/test.py
fs/time.py
fs/walk.py
fs/wrap.py
fs/wrapfs.py
fs/zipfs.py
setup.cfg
tests/test_doctest.py

- Tests
This PR addresses some documentation issues. I also added a `unittest` loader so that the documentation examples are now tested with the other unit tests. This will prevent the documentation from having out-of-date examples.
- Closes #441
- Closes #423 
- Closes #410
- Closes #300
- Closes #471 
- Closes #469

Update docs and add doctest loading mechanism

---

CHANGELOG.md
fs/_bulk.py
fs/base.py
fs/copy.py
fs/ftpfs.py
fs/memoryfs.py
fs/mirror.py
fs/move.py
fs/osfs.py
fs/wrap.py
fs/wrapfs.py
setup.cfg
tests/requirements.txt
tests/test_copy.py
tests/test_ftpfs.py
tests/test_memoryfs.py
tests/test_mirror.py
tests/test_move.py
tests/test_opener.py
tests/test_osfs.py
tests/test_wrap.py

- New feature
Fixes #450 by adding a `preserve_time` parameter to all relevant functions. The parameter is `False` by default to retain previous behaviour. However, it could be argued that the default should be `True` to mimic more common behavior found in operating systems.

Added preserve_time parameter to move, copy, and mirror

---

CHANGELOG.md
fs/info.py
fs/osfs.py
fs/test.py
tests/test_osfs.py

- Bug fix
Unit tests for `FS.setinfo` now function correctly, whereas they basically did nothing before. Also, a bug in OSFS was fixed which caused timestamps to lose precision with `setinfo`.

Some setinfo fixes

---

CONTRIBUTORS.md
docs/source/extension.rst
docs/source/openers.rst
fs/base.py
fs/subfs.py

As requested in #501 we should be making a new release soon. Before this, there are some documentation points that should be addressed (the actual fixes / enhancements not merged yet will wait until next release):

Update documentation for `v2.4.14`

---

CHANGELOG.md
fs/errors.py
fs/memoryfs.py
fs/test.py

- Bug fix
Fix `MemoryFS.move` and `MemoryFS.movedir` not renaming the entry that gets moved, which is causing issues with `scandir` (#509). This was not being picked by current tests, so I updated the `test_move_file_same_fs` and `test_move_dir_same_fs` test cases to detect the issue before fixing it.

Fix `move` and `movedir` methods of `MemoryFS` not renaming the entry

---

CHANGELOG.md
fs/wrapfs.py

- Bug fix
The current implementation of `WrapFS.move` and `WrapFS.movedir` was always going through the `fs.move` functions. For `move`, this was just causing one extra call (`WrapFS.move -> fs.move.move_file -> WrapFS.delegate_fs().move`). But for `movedir`, this was never the case (`fs.move.move_dir` is always copying/removing the files, and never tries to call `movedir` because of recursivity issues, **this should be fixed too at some point**):
```python
home_fs = open_fs("~")
pics_fs = home_fs.opendir("Pictures")
pics_fs.movedir("My kid", "My kids")  # this was never using `home_fs.movedir`, always copying files
```

Update `movedir` methods of `WrapFS` to use the delegate FS method

---

.github/workflows/test.yml

- Other
This avoids the need to play whack-a-mole with CI failures, like I had to deal with on #518. Everything should be laid out on the table once. This saves everyone time.

Don't fail fast when running tests

---

CHANGELOG.md
fs/_ftp_parse.py
fs/_tzcompat.py
fs/test.py
fs/time.py
setup.cfg
tests/test_info.py
tests/test_time.py

- Other
Everything that pytz was being utilised for can be serviced perfectly
fine by the standard library. Meanwhile, pytz is known as a footgun:
https://blog.ganssle.io/articles/2018/03/pytz-fastest-footgun.html
Fixes #516

Remove pytz

---

CHANGELOG.md
CONTRIBUTORS.md
fs/appfs.py
setup.cfg
tests/test_appfs.py
tests/test_opener.py

- Other
Use the better maintained `platformdirs` instead of `appdirs`.

Use platformdirs instead of appdirs

---

CHANGELOG.md
fs/zipfs.py

- Bug fix
This PR fixes two things with the `ReadZipFS` class:
- Use the native mechanism implemented in `zipfile` for seeking files inside of Zip archives, instead of emulating it by re-opening and reading files.
- Mark `ReadZipFS` as case-sensitive, since Zip archives are case-sensitive.

Update `ReadZipFS.openbin` handler to use native Python `zipfile` code

---

CHANGELOG.md
fs/base.py
fs/errors.py
fs/glob.py
fs/walk.py
fs/wildcard.py
tests/test_glob.py
tests/test_walk.py

- New feature
Fixes #371. Fixes #459 .
Added parameters `filter_glob` and `exclude_glob` to `fs.walk.Walker` to perform selection on the walked resources based on their global path.

Add `filter_glob` and `exclude_glob` to fs.walk

---

docs/source/info.rst

There is a small typo in docs/source/info.rst.
Should read `filesystem` rather than `fileystem`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: fix simple typo, fileystem -> filesystem

---

.github/workflows/test.yml

- Other
As discussed in #547, the tests should time out faster than the default 6h. I looked at some previous test runs and they all finish in 1:30 to 3:00 minutes. So I guess a 10:00 minute timeout should be fine.

Github Actions Timeout

---

CHANGELOG.md
fs/base.py
fs/copy.py
fs/errors.py
fs/memoryfs.py
fs/osfs.py
fs/test.py
fs/wrapfs.py

- Bug fix
- Tests
Draft PR for fixing #546.

Bugfix: File deleted / emptied when moved / copied onto itself (#546)

---

CHANGELOG.md
fs/move.py
tests/test_move.py

- Bug fix
- Tests
Added `overwrite=True` to the optimized path in `fs.move.move_file`. `move_file` now behaves like in versions <2.4.16.

Fix backward incompatibility introduced in 2.4.16 (#535)
