- docs/source/info.rst
- fs/copy.py
- tests/test_copy.py
Some tests to bring coverage back to 100%
Also made some changes for formatting, and a little re-structuring for brevity. Should be no change to functionality.
> formatting and coverage for copy_if_newer

- docs/source/external.rst
* Add `fs.smbfs` and `fs.sshfs`
* Add CI badge in filesystem section header
> Update external FS page with personal contributions

- fs/osfs.py
> fix grammar ("root path does not exists" => "exist")

- setup.cfg
Signed-off-by: Philippe Ombredanne <pombredanne@nexb.com>
> Ensure LICENSE file is included in built wheels

- fs/base.py
- fs/compress.py
- fs/filesize.py
- fs/ftpfs.py
- fs/opener/errors.py
- fs/opener/ftpfs.py
- fs/permissions.py
- fs/tempfs.py
- fs/zipfs.py
- tests/test_opener.py
> add proxy support to ftp

- fs/tarfs.py
- tests/test_archives.py
- tests/test_tarfs.py
- tests/test_zipfs.py
Fixes encoding issue on Py27 with TarFS (https://github.com/PyFilesystem/pyfilesystem2/issues/137)
> tarfs encoding fix

- CHANGELOG.md
- fs/__init__.py
- fs/_fscompat.py
- fs/_version.py
- fs/base.py
- fs/info.py
- fs/osfs.py
- fs/permissions.py
- fs/test.py
- requirements.txt
- setup.py
- tests/test_encoding.py
- tests/test_osfs.py
- tox.ini
Attempt to tackle broken unicode filenames on Linux 
FIxes https://github.com/PyFilesystem/pyfilesystem2/issues/120
> handle broken unicode paths

- fs/opener/ftpfs.py
- tests/test_ftpfs.py
Ported fix from fs.sshfs
All credit to @althonos
https://github.com/althonos/fs.sshfs/commit/48664f2251e1d5c80dc4cf9bb36014a3cde3880d
> Honor `create` option in opener

- docs/source/introduction.rst
> Add conda install command to docs

- fs/test.py
Check times are of correct type in raw info.
> check times types

- CHANGELOG.md
- fs/ftpfs.py
- tests/test_ftpfs.py
Fix for https://github.com/PyFilesystem/pyfilesystem2/issues/205
> fix for ftp dir listing

- fs/osfs.py
replace:
_stat = os.lstat(fsencode(sys_path))
with:
_lstat = os.lstat(fsencode(sys_path))
> osfs.py: getinfo: replace _stat with _lstat

- fs/info.py
> Mis-spelling in comments

- fs/_version.py
- fs/memoryfs.py
- fs/test.py
Fix for https://github.com/PyFilesystem/pyfilesystem2/issues/221
> fix Schrödinger memory resource

- tests/test_archives.py
Travis was reporting this test fail:
```
======================================================================
FAIL: test_getinfo (tests.test_tarfs.TestReadTarFS)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/home/travis/build/PyFilesystem/pyfilesystem2/tests/test_tarfs.py", line 185, in test_getinfo
super(TestReadTarFS, self).test_getinfo()
File "/home/travis/build/PyFilesystem/pyfilesystem2/tests/test_archives.py", line 81, in test_getinfo
self.assertEqual(top.permissions.mode, 0o644)
AssertionError: 436 != 420
======================================================================
FAIL: test_getinfo (tests.test_zipfs.TestReadZipFS)
----------------------------------------------------------------------
Traceback (most …
```
> fix permissions test fail in archive

- CHANGELOG.md
- fs/_version.py
- fs/base.py
Fixes https://github.com/PyFilesystem/pyfilesystem2/issues/267
Please describe your changes here. If this fixes a bug, please link to the issue, if possible.
> Fix exception when Python is run with -OO

- CHANGELOG.md
- fs/_version.py
- fs/base.py
- fs/osfs.py
Handle OSError in os.pathconf, to fix https://github.com/PyFilesystem/pyfilesystem2/issues/217
> handle missing path max

- CHANGELOG.md
- fs/_version.py
- fs/base.py
https://github.com/PyFilesystem/pyfilesystem2/issues/278
> restored setfile

- tests/test_ftpfs.py
> Test for geturl() method

- tests/test_copy.py
Fixes https://github.com/PyFilesystem/pyfilesystem2/issues/285.
> base the file's new utime on current UTC time

- CHANGELOG.md
- fs/__init__.py
- tests/test_imports.py
Fix for https://github.com/PyFilesystem/pyfilesystem2/issues/304
> fix fs.path import

- CHANGELOG.md
- fs/base.py
Fix for https://github.com/PyFilesystem/pyfilesystem2/issues/298
> close filesystem on delete

- CHANGELOG.md
- fs/base.py
https://github.com/PyFilesystem/pyfilesystem2/issues/310
> Fix makedirs

- CHANGELOG.md
- fs/base.py
- fs/wrapfs.py
https://github.com/PyFilesystem/pyfilesystem2/issues/294
> Add missing methods to WrapFS

- CHANGELOG.md
- fs/wrapfs.py
Fixes https://github.com/PyFilesystem/pyfilesystem2/issues/322
> fix movedir

- docs/source/globbing.rst
> Fix simple typo: recusrive -> recursive
